x=input("x = ")
y=input("y = ")
print(x,y)
print(x*5,y*3)
print(x+y)
x=float(x)
y=float(y)
print("x = %f, y = %f, x ? y = %d" % (x,y,int(x)**int(y)))
print("%d" % (x/y))
print(x//y)
x=int(input("x = "))
y=int(input("y = "))
print(x/y)
print(x//y)