n1=float(input("Enter the first number: "))
n2=float(input("Enter the second number: "))
n3=float(input("Enter the third number: "))
print(f"Max = {max(n1,n2,n3)}\nMin = {min(n1,n2,n3)}")
print("Sorted = ",sorted([n1,n2,n3]))